steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REGISTRY/$WAS', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REGISTRY/$WAS']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'artifacts'
      - 'docker'
      - 'pull'
      - 'gcr.io/$PROJECT_ID/$REGISTRY/$WAS'
      - '--tag=us-docker.pkg.dev/$PROJECT_ID/$REGISTRY/$WAS'

options:
  logging: 'NONE'
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _REPO_NAME: ${REGISTRY}
  _BRANCH_NAME: main
  _SHORT_SHA: ${SHORT_SHA}
  REGISTRY: ${WAS}
